Update nuxtjs.yml

diff --git a/.github/workflows/nuxtjs.yml b/.github/workflows/nuxtjs.yml
--- a/.github/workflows/nuxtjs.yml
+++ b/.github/workflows/nuxtjs.yml
@@ -18,6 +18,28 @@ permissions:
   pages: write
   id-token: write
 
+# 新代码开始
+- name: Detect package manager
+  id: detect-package-manager
+  run: |
+    if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+      echo "manager=yarn" >> $GITHUB_OUTPUT
+      echo "command=install" >> $GITHUB_OUTPUT
+      exit 0
+    elif [ -f "${{ github.workspace }}/package.json" ]; then
+      echo "manager=npm" >> $GITHUB_OUTPUT
+      echo "command=ci" >> $GITHUB_OUTPUT
+      exit 0
+    elif [ -d "${{ github.workspace }}/node_modules" ]; then
+      echo "manager=npm" >> $GITHUB_OUTPUT
+      echo "command=ci" >> $GITHUB_OUTPUT
+      exit 0
+    else
+      echo "Unable to determine package manager"
+      exit 1
+    fi
+# 新代码结束
+
 # Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
 # However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
